warmer.settings:
  type: config_object
  label: 'Warmer Settings'
  mapping:
    warmers:
      type: sequence
      label: 'Warmers'
      sequence:
        type: warmer.settings.warmer_plugin.[%key]
