warmer.settings.warmer_plugin.entity:
  type: mapping
  mapping:
    id:
      type: string
    frequency:
      type: integer
    batchSize:
      type: integer
    entity_types:
      type: sequence
      sequence:
        type: string
