warmer.settings.warmer_plugin.jsonapi:
  type: mapping
  mapping:
    id:
      type: string
    frequency:
      type: integer
    batchSize:
      type: integer
    resource_types:
      type: sequence
      sequence:
        type: string
